import AntdStyledComponentsRegistry from '@/components/providers/AntdStyledComponentsRegistry';
import QueryClientProviderWrapper from '@/components/providers/QueryClientProviderWrapper';
import AutoSlide from '@/components/sections/AutoSlide';
import Banner from '@/components/sections/Banner';
import CTASection from '@/components/sections/CTASection';
import FAQSection from '@/components/sections/FAQSection';
import Footer from '@/components/sections/Footer';
import HeaderSection from '@/components/sections/Header';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { App, ConfigProvider } from 'antd';
import type { Metadata } from 'next';
import { ViewTransitions } from 'next-view-transitions';
import { Geist, Geist_Mono } from 'next/font/google';
import NextTopLoader from 'nextjs-toploader';
import '../styles/globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang='en'>
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <AntdStyledComponentsRegistry>
            <QueryClientProviderWrapper>
              <ConfigProvider theme={{ cssVar: true }}>
                <NextTopLoader color='#1677ff' showSpinner={false} />
                <div className='relative flex min-h-screen flex-col'>
                  <HeaderSection />

                  <div className='mt-[64px]'>
                    <Banner />
                  </div>

                  <div className='mx-auto w-full max-w-[1615px] flex-1'>
                    <AntdRegistry>
                      <App notification={{ maxCount: 1 }}>{children}</App>
                    </AntdRegistry>
                  </div>

                  <div className='flex flex-col gap-8'>
                    <FAQSection />
                    <AutoSlide />
                    <CTASection />
                  </div>
                  <Footer />
                </div>
              </ConfigProvider>
            </QueryClientProviderWrapper>
          </AntdStyledComponentsRegistry>
        </body>
      </html>
    </ViewTransitions>
  );
}
