import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import { HeroProviderBase } from "@/components/providers/HeroProviderBase";
import HeaderSection from "@/components/sections/Header";
import Footer from "@/components/sections/Footer";
import CTASection from "@/components/sections/CTASection";
import { ViewTransitions } from 'next-view-transitions'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ViewTransitions>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <HeroProviderBase>
            <div className="flex flex-col min-h-screen">
              <HeaderSection />
              <div className="flex-1 px-6 pt-6 max-w-[1615px] mx-auto w-full">{children}</div>
              <CTASection/>
              <Footer/>
            </div>
          </HeroProviderBase>
        </body>
      </html>
    </ViewTransitions>

  );
}
